image:
  repository: khoaitaybeo86/kube-sidecar-injector
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 1

service:
  port: 443

container:
  port: 8443

podAnnotations: {}
podLabels: {}
podSecurityContext: {}

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1024Mi"

sidecars:
  dataKey: sidecars.yaml

selectors:
  injectPrefix: sidecar-injector.expedia.com
  injectName: inject
  disableInjectLabel: disable-inject
  objectSelector: {}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - kube-public
